server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 37017
      database: local
cache:
  hostname: localhost
  password: Redis2022!
  port: 6379
  ttl: 24h
feign:
  url: 'https://swapi.dev/api/'
logging:
  file:
    name: logs/log.txt