services:
  mongo:
    container_name: mongo.space
    image: mongo
    ports:
      - "37017:27017"
    networks:
      - bubble

  redis:
    container_name: redis.space
    image: redis
    command: redis-server --requirepass Redis2022!
    ports:
      - "6379:6379"

networks:
  bubble:
    external: true